CREATE TABLE
    DOCUMENTO (
        IDDOCUMENTO INT PRIMARY KEY AUTO_INCREMENT,
        NSU CHAR(15) NOT NULL,
        DOC_SCHEMA VARCHAR(13) NOT NULL,
        CONTEUDO TEXT,
        PROCESSADO BOOLEAN DEFAULT FALSE,
        DATA_CRIACAO DATETIME DEFAULT NOW()
    );

CREATE TABLE
    HISTORICO (
        IDHISTORICO INT PRIMARY KEY AUTO_INCREMENT,
        NSU_CONSULTADO INT,
        ULTIMO_NSU INT,
        MAIOR_NSU INT,
        STATUS CHAR(3),
        MOTIVO VARCHAR(255),
        DATA_RESPOSTA DATETIME,
        AMBIENTE CHAR(1),
        RESPOSTA LONGTEXT,
        DATA_CRIACAO DATETIME DEFAULT NOW()
    );

CREATE TABLE
    NFE (
        IDNFE INT PRIMARY KEY AUTO_INCREMENT,
        NSU VARCHAR(15) NOT NULL,
        CHAVE_ACESSO CHAR(44) NOT NULL,
        CNPJ CHAR(14) NOT NULL,
        CPF CHAR(11) NOT NULL,
        RAZAO_SOCIAL VARCHAR(60) NOT NULL,
        IE VARCHAR(14) NOT NULL,
        DATA_EMISSAO DATETIME,
        DATA_AUTORIZACAO DATETIME,
        TIPO_OPERACAO CHAR(1),
        VALOR_TOTAL DECIMAL(15, 2),
        PROTOCOLO CHAR(15),
        SITUACAO_NFE CHAR(1),
        XML TEXT,
        ID_DOCUMENTO INT,
        DATA_CRIACAO DATETIME DEFAULT NOW(),
        FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(IDDOCUMENTO)
    );

CREATE TABLE
    EVENTO (
        IDEVENTO INT PRIMARY KEY AUTO_INCREMENT,
        NSU VARCHAR(15) NOT NULL,
        CHAVE_ACESSO CHAR(44) NOT NULL,
        CNPJ CHAR(14) NOT NULL,
        CPF CHAR(11) NOT NULL,
        DATA_EVENTO DATETIME,
        TIPO_EVENTO CHAR(6) NOT NULL,
        SEQUENCIA INT(2) NOT NULL,
        DESCRICAO_EVENTO VARCHAR(60),
        DATA_AUTORIZACAO DATETIME,
        PROTOCOLO CHAR(15),
        XML TEXT,
        ID_DOCUMENTO INT,
        DATA_CRIACAO DATETIME DEFAULT NOW(),
        FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(IDDOCUMENTO)
    );

# Indices

ALTER TABLE NFE ADD INDEX IDX_NFE_CHAVE_ACESSO (CHAVE_ACESSO);

ALTER TABLE NFE ADD INDEX IDX_NFE_CNPJ (CNPJ);

ALTER TABLE EVENTO ADD INDEX IDX_EVENTO_CHAVE_ACESSO (CHAVE_ACESSO);

ALTER TABLE EVENTO ADD INDEX IDX_EVENTO_CNPJ (CNPJ);