version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radar-app
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html/
      - ./php.ini-development:/usr/local/etc/php/conf.d/php.ini
  db:
    container_name: radar-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_radar:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    command: [ 'mysqld', '--default-time-zone=-03:00' ]
volumes:
  mysql_data_radar:
